INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (1, 'COUNTRY', 'India', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (2, 'COUNTRY', 'USA', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (3, 'COUNTRY', 'UK', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (4, 'COUNTRY', 'Germany', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (5, 'COUNTRY', 'Canada', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (6, 'COUNTRY', 'Australia', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (7, 'COUNTRY', 'UAE', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (8, 'COUNTRY', 'Singapore', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (9, 'COUNTRY', 'France', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (10, 'COUNTRY', 'Brazil', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (11, 'CITY', 'Hyderabad', 1);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (12, 'CITY', 'Mumbai', 1);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (13, 'CITY', 'Delhi', 1);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (14, 'CITY', 'New York', 2);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (15, 'CITY', 'San Francisco', 2);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (16, 'CITY', 'London', 3);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (17, 'CITY', 'Berlin', 4);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (18, 'CITY', 'Toronto', 5);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (19, 'CITY', 'Melbourne', 6);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (20, 'CITY', 'Dubai', 7);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (21, 'CITY', 'Singapore', 8);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (22, 'CITY', 'Paris', 9);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (23, 'CITY', 'Rio de Janeiro', 10);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (24, 'CITY', 'Chennai', 1);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (25, 'CITY', 'Chicago', 2);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (26, 'DEPARTMENT', 'HR', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (27, 'DEPARTMENT', 'Finance', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (28, 'DEPARTMENT', 'Engineering', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (29, 'DEPARTMENT', 'Operations', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (30, 'DEPARTMENT', 'Marketing', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (31, 'DEPARTMENT', 'Sales', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (32, 'DEPARTMENT', 'Legal', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (33, 'DEPARTMENT', 'IT Support', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (34, 'DEPARTMENT', 'Research and development', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (35, 'DEPARTMENT', 'Procurement', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (36, 'BAND', 'A1', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (37, 'BAND', 'A2', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (38, 'BAND', 'B1', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (39, 'BAND', 'B2', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (40, 'BAND', 'C1', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (41, 'SKILL', 'Java', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (42, 'SKILL', 'Python', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (43, 'SKILL', 'Angular', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (44, 'SKILL', 'React', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (45, 'SKILL', 'Node.js', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (46, 'SKILL', 'PL/SQL', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (47, 'SKILL', 'C#', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (48, 'SKILL', 'DevOps', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (49, 'SKILL', 'AWS', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (50, 'SKILL', 'Docker', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (51, 'SKILL', 'Kubernetes', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (52, 'SKILL', 'HTML', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (53, 'SKILL', 'CSS', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (54, 'SKILL', 'Spring', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (55, 'SKILL', 'Express', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (56, 'JOB_TITLE', 'Software Engineer', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (57, 'JOB_TITLE', 'HR Executive', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (58, 'JOB_TITLE', 'Finance Analyst', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (59, 'JOB_TITLE', 'DevOps Engineer', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (60, 'JOB_TITLE', 'UI/UX Designer', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (61, 'JOB_TITLE', 'Sales Manager', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (62, 'JOB_TITLE', 'Product Manager', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (63, 'JOB_TITLE', 'System Administrator', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (64, 'JOB_TITLE', 'QA Engineer', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (65, 'JOB_TITLE', 'Backend Developer', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (66, 'DEGREE', 'B.Tech', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (67, 'DEGREE', 'M.Tech', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (68, 'DEGREE', 'MBA', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (69, 'DEGREE', 'B.Sc', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (70, 'DEGREE', 'M.Sc', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (71, 'DEGREE', 'BA', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (72, 'ID_PROOF_TYPE', 'Aadhar', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (73, 'ID_PROOF_TYPE', 'Passport', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (74, 'ID_PROOF_TYPE', 'PAN Card', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (75, 'ID_PROOF_TYPE', 'Driving License', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (76, 'EXIT_REASON', 'Resignation', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (77, 'EXIT_REASON', 'Retirement', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (78, 'EXIT_REASON', 'Termination', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (79, 'EXIT_REASON', 'Health Reasons', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (80, 'EXIT_REASON', 'Relocation', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (81, 'EXIT_REASON', 'Better Opportunity', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (82, 'PERFORMANCE_RATING', '1', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (83, 'PERFORMANCE_RATING', '2', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (84, 'PERFORMANCE_RATING', '3', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (85, 'PERFORMANCE_RATING', '4', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (86, 'PERFORMANCE_RATING', '5', NULL);

