--insert into master data

INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (1, 'COUNTRY', 'India', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (2, 'COUNTRY', 'USA', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (3, 'COUNTRY', 'UK', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (4, 'CITY', 'Hyderabad', 1);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (5, 'CITY', 'Bengaluru', 1);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (6, 'CITY', 'New Delhi', 1);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (7, 'CITY', 'New York', 2);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (8, 'CITY', 'San Francisco', 2);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (9, 'CITY', 'London', 3);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (10, 'CITY', 'Manchester', 3);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (11, 'DEPARTMENT', 'Engineering', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (12, 'DEPARTMENT', 'HR', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (13, 'DEPARTMENT', 'Finance', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (14, 'DEPARTMENT', 'Operations', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (15, 'BAND', 'A1', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (16, 'BAND', 'B1', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (17, 'BAND', 'C1', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (18, 'SKILL', 'Java', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (19, 'SKILL', 'PL/SQL', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (20, 'SKILL', 'Angular', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (21, 'SKILL', 'Python', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (22, 'SKILL', 'React', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (23, 'EXIT_REASON', 'Personal', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (24, 'EXIT_REASON', 'Better Opportunity', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (25, 'EXIT_REASON', 'Health Issues', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (26, 'EXIT_REASON', 'Relocation', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (27, 'EXIT_REASON', 'Retirement', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (28, 'JOB_TITLE', 'Software Engineer', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (29, 'JOB_TITLE', 'HR Executive', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (30, 'JOB_TITLE', 'Finance Analyst', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (31, 'JOB_TITLE', 'DevOps Engineer', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (32, 'JOB_TITLE', 'Business Analyst', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (33, 'DEGREE', 'B.Tech', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (34, 'DEGREE', 'M.Tech', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (35, 'DEGREE', 'MBA', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (36, 'DEGREE', 'B.Sc', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (37, 'DEGREE', 'M.Sc', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (38, 'ID_PROOF_TYPE', 'Aadhar', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (39, 'ID_PROOF_TYPE', 'Passport', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (40, 'ID_PROOF_TYPE', 'Driving License', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (41, 'PERFORMANCE_RATING', '1', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (42, 'PERFORMANCE_RATING', '2', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (43, 'PERFORMANCE_RATING', '3', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (44, 'PERFORMANCE_RATING', '4', NULL);
INSERT INTO master_data (masterdata_id, masterdata_type, masterdata_value, parent_id) VALUES (45, 'PERFORMANCE_RATING', '5', NULL);